[package]
name = "sage-tauri"
version = "0.1.0"
description = "A next generation Chia wallet."
authors = ["Rigidity <me@rigidnetwork.com>"]
license = "Apache-2.0"
repository = "https://github.com/rigidity/sage"
edition = "2021"
rust-version = "1.70"

[lib]
name = "sage_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
sage = { workspace = true }
sage-client = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tauri = { workspace = true, features = [] }
bip39 = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
thiserror = { workspace = true }
tauri-plugin-clipboard-manager = { workspace = true }
tokio = { workspace = true }
bincode = { workspace = true }
toml = { workspace = true, features = ["preserve_order"] }
indexmap = { workspace = true, features = ["serde"] }
hex = { workspace = true }
chia = { workspace = true }
itertools = { workspace = true }
sqlx = { workspace = true, features = ["sqlite", "runtime-tokio"] }

[build-dependencies]
tauri-build = { workspace = true, features = [] }
