[package]
name = "sage-tauri"
version = "0.1.0"
description = "A next generation Chia wallet."
authors = ["Rigidity <me@rigidnetwork.com>"]
license = "Apache-2.0"
repository = "https://github.com/rigidity/sage"
edition = "2021"
rust-version = "1.70"

[lib]
name = "sage_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-beta.17", features = [] }

[dependencies]
serde_json = "1.0.118"
serde = { version = "1.0.203", features = ["derive"] }
tauri = { version = "2.0.0-beta.23", features = [] }
sage = { path = "../sage" }
bip39 = "2.0.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
thiserror = "1.0.61"
tauri-plugin-clipboard-manager = "2.1.0-beta.5"
tokio = "1.38.0"
bincode = "1.3.3"
toml = { version = "0.8.14", features = ["preserve_order"] }
indexmap = { version = "2.2.6", features = ["serde"] }
chia-wallet-sdk = "0.11.0"
hex = "0.4.3"
chia = "0.9.0"
itertools = "0.13.0"
toml_edit = { version = "0.22.15", features = ["serde"] }
