[package]
name = "sage-tauri"
version = "0.1.0"
description = "A next generation Chia wallet."
authors = ["Rigidity <me@rigidnetwork.com>"]
license = "Apache-2.0"
repository = "https://github.com/rigidity/sage"
edition = "2021"

[lints]
workspace = true

[lib]
name = "sage_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[dependencies]
sage-api = { workspace = true }
sage-config = { workspace = true }
sage-database = { workspace = true }
sage-keychain = { workspace = true }
sage-wallet = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_with = { workspace = true, features = ["hex"] }
tauri = { workspace = true, features = [] }
tauri-specta = { workspace = true, features = ["derive", "typescript"] }
specta = { workspace = true }
specta-typescript = { workspace = true }
bip39 = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
thiserror = { workspace = true }
tauri-plugin-clipboard-manager = { workspace = true }
tokio = { workspace = true }
bincode = { workspace = true }
toml = { workspace = true, features = ["preserve_order"] }
indexmap = { workspace = true, features = ["serde"] }
hex = { workspace = true }
chia = { workspace = true }
chia-wallet-sdk = { workspace = true, features = ["rustls"] }
clvmr = { workspace = true }
itertools = { workspace = true }
sqlx = { workspace = true, features = ["sqlite", "runtime-tokio"] }
futures-util = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
futures-lite = { workspace = true }
rayon = { workspace = true }
log = { workspace = true }
bigdecimal = { workspace = true }
bech32 = { workspace = true }

[build-dependencies]
tauri-build = { workspace = true, features = [] }
