[workspace]
members = ["sage", "src-tauri"]
resolver = "2"

[workspace.lints.rust]
rust_2018_idioms = { level = "deny", priority = -1 }
rust_2021_compatibility = { level = "deny", priority = -1 }
future_incompatible = { level = "deny", priority = -1 }
nonstandard_style = { level = "deny", priority = -1 }
unsafe_code = "deny"
non_ascii_idents = "deny"
unused_extern_crates = "deny"
trivial_casts = "deny"
trivial_numeric_casts = "deny"
unreachable_pub = "warn"
unreachable_code = "warn"
unreachable_patterns = "warn"
dead_code = "warn"
deprecated = "deny"
deprecated_in_future = "deny"
missing_debug_implementations = "warn"
missing_copy_implementations = "warn"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
cargo = { level = "allow", priority = -1 }
pedantic = { level = "warn", priority = -1 }
too_many_lines = "allow"
missing_errors_doc = "allow"
missing_panic_doc = "allow"
module_name_repetitions = "allow"
multiple_crate_versions = "allow"
must_use_candidate = "allow"

[workspace.dependencies]
sage = { path = "./sage" }
serde_json = "1.0.118"
serde = "1.0.203"
tauri = "2.0.0-beta.23"
bip39 = "2.0.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
thiserror = "1.0.61"
tauri-plugin-clipboard-manager = "2.1.0-beta.5"
tokio = "1.38.0"
bincode = "1.3.3"
toml = "0.8.14"
indexmap = "2.2.6"
chia-wallet-sdk = "0.11.0"
hex = "0.4.3"
chia = "0.9.0"
itertools = "0.13.0"
toml_edit = "0.22.15"
sqlx = "0.7.4"
tauri-build = "2.0.0-beta.17"
clvmr = "0.7.0"
anyhow = "1.0.86"
serde_with = { version = "3.8.2" }
tokio-tungstenite = { version = "0.23.1", features = ["native-tls"] }
tungstenite = "0.23.0"
futures-util = "0.3.30"
log = "0.4.22"
native-tls = "0.2.12"
sha2 = "0.10.8"
aes-gcm = "0.10.3"
argon2 = "0.5.3"
