name: Build
on:
  push:
    branches:
      - main
    tags:
      - '**'

  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install GTK
        run: sudo apt-get install libgtk-3-dev libjavascriptcoregtk-4.1-dev libwebkit2gtk-4.1-dev

      - name: Cargo binstall
        run: curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash

      - name: Clippy
        run: cargo clippy --workspace --all-features --all-targets

      - name: Unused dependencies
        run: |
          cargo binstall cargo-machete --locked -y
          cargo machete

      - name: Fmt
        run: cargo fmt --all -- --files-with-diff --check

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Bundle
        run: CI=true pnpm tauri build --ci

      - uses: actions/upload-artifact@v4
        with:
          name: macos
          path: |
            ./target/aarch64-apple-darwin/release/bundle/macos/*.app
            ./target/aarch64-apple-darwin/release/bundle/dmg/*.dmg
